### ISSUE TITLE
Organizers Yaml

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#26]
I pulled enough information out of Trello to get our organizers yaml started. Please update or add your information to the following: https://github.com/djangocon/2017.djangocon.us/blob/design/_data/organizers.yml

Here's an example of mine:

```yaml
  - name: "Jeff Triplett"
    role: "Delegator and DEFNA President"
    photo_url: "/static/img/organizers/jeff.jpg"
    github: "jefftriplett"
    twitter: "webology"
    website: "https://jefftriplett.com/"
```

**Please note** that the `hidden: false` was removed above.

We also need a photo (**600x600**) from everyone which should be the `photo_url`. 

These are stored in the `static/img/organizers` folder.
